import { invoke } from '../lib/tauri';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import type {
  AppSettings,
  ApprovalEntry,
  ApprovalLevel,
  ApprovalScope,
  BgAgentSummary,
  PersistentApprovalEntry,
  RefineHandoff,
  RerunVariant,
  SessionId,
  ToolCallId,
} from '@forge/ipc';

export const SESSION_EVENT = 'session:event';

/** Mirror of `forge_ipc::HelloAck`. */
export interface HelloAck {
  session_id: string;
  workspace: string;
  started_at: string;
  event_seq: number;
  schema_version: number;
}

/** Payload emitted by the shell's bridge reader task. */
export interface SessionEventPayload {
  session_id: SessionId;
  seq: number;
  event: unknown;
}

/**
 * F-052 (H11 / T7): `session_hello` takes no socket-path override. The Rust
 * command has no `socketPath` parameter — any such field in the invoke
 * payload is silently dropped by serde before the command runs, and the
 * shell resolves the UDS exclusively via `default_socket_path(session_id)`.
 * Do not add a second argument here; it would be unused at runtime and
 * obscure the invariant that the webview cannot steer this connection.
 */
export async function sessionHello(sessionId: SessionId): Promise<HelloAck> {
  return invoke<HelloAck>('session_hello', { sessionId });
}

export async function sessionSubscribe(
  sessionId: SessionId,
  since = 0,
): Promise<void> {
  await invoke('session_subscribe', { sessionId, since });
}

export async function sessionSendMessage(
  sessionId: SessionId,
  text: string,
): Promise<void> {
  await invoke('session_send_message', { sessionId, text });
}

export async function sessionApproveTool(
  sessionId: SessionId,
  toolCallId: ToolCallId,
  scope: ApprovalScope,
): Promise<void> {
  await invoke('session_approve_tool', { sessionId, toolCallId, scope });
}

export async function sessionRejectTool(
  sessionId: SessionId,
  toolCallId: ToolCallId,
  reason?: string,
): Promise<void> {
  await invoke('session_reject_tool', { sessionId, toolCallId, reason });
}

// ---------------------------------------------------------------------------
// F-036: persistent approval commands
// ---------------------------------------------------------------------------

/**
 * Load all persistent approvals (workspace + user) for seeding the per-session
 * whitelist at session start. Workspace entries win on `scope_key` collision
 * with user entries (mirrors `forge-mcp::config::load_merged`).
 *
 * `PersistentApprovalEntry` is generated by ts-rs from the Rust shape in
 * `forge-shell::ipc` — keep the two in sync by regenerating after any field
 * change, not by patching this file.
 */
export async function getPersistentApprovals(
  workspaceRoot: string,
): Promise<PersistentApprovalEntry[]> {
  return invoke<PersistentApprovalEntry[]>('get_persistent_approvals', {
    workspaceRoot,
  });
}

/**
 * Upsert `entry` into the config for `level`. Session-level saves are a no-op
 * on the backend but remain defensively accepted so a mis-routed caller fails
 * soft. Frontend call-sites should skip the invoke for `'session'` to avoid
 * an unnecessary round trip.
 */
export async function saveApproval(
  entry: ApprovalEntry,
  level: ApprovalLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('save_approval', { entry, level, workspaceRoot });
}

/**
 * Drop the matching entry from the config for `level`. Session-level removal
 * is a no-op on the backend for the same reason as `saveApproval`.
 */
export async function removeApproval(
  scopeKey: string,
  level: ApprovalLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('remove_approval', { scopeKey, level, workspaceRoot });
}

/**
 * Subscribe to session events from the shell. Returns an unlisten handle.
 * The callback receives the payload unwrapped from Tauri's event envelope.
 */
export async function onSessionEvent(
  handler: (payload: SessionEventPayload) => void,
): Promise<UnlistenFn> {
  return listen<SessionEventPayload>(SESSION_EVENT, (event) => {
    handler(event.payload);
  });
}

// ---------------------------------------------------------------------------
// F-137 / F-138: background-agent lifecycle commands.
//
// The Status-bar `BgAgentsBadge` (F-138) calls `listBackgroundAgents` on mount
// (post-reconnect recovery) and subscribes to `session:event` for live
// lifecycle updates. Popover Promote/Stop buttons route through
// `promoteBackgroundAgent` / `stopBackgroundAgent`.
// ---------------------------------------------------------------------------

export async function listBackgroundAgents(
  sessionId: SessionId,
): Promise<BgAgentSummary[]> {
  return invoke<BgAgentSummary[]>('list_background_agents', { sessionId });
}

export async function promoteBackgroundAgent(
  sessionId: SessionId,
  instanceId: string,
): Promise<void> {
  await invoke('promote_background_agent', { sessionId, instanceId });
}

export async function stopBackgroundAgent(
  sessionId: SessionId,
  instanceId: string,
): Promise<void> {
  await invoke('stop_background_agent', { sessionId, instanceId });
}

// ---------------------------------------------------------------------------
// F-365: session control commands
// ---------------------------------------------------------------------------

/** Cancel the in-flight turn for the session (F-391). */
export async function sessionCancel(sessionId: SessionId): Promise<void> {
  await invoke('session_cancel', { sessionId });
}

/**
 * F-603: pause the session orchestrator at the next inter-step checkpoint.
 * Idempotent backend; the `Running → Paused` transition arrives via
 * `Event::SessionPaused` on the session event stream.
 */
export async function sessionPause(sessionId: SessionId): Promise<void> {
  await invoke('session_pause', { sessionId });
}

/**
 * F-640: forward the dashboard's `provider:changed` event onto a session's
 * UDS so the in-process daemon swaps the active provider for the next
 * turn. In-flight turns finish on the previous provider —
 * `SwappableProvider::swap` snapshots the inner at chat-call time, so a
 * mid-stream swap does not affect the running turn.
 *
 * `providerId` matches the dashboard's `[providers.active]` shape
 * (`"ollama"`, `"anthropic"`, `"openai"`, `"custom_openai:<name>"`). Unknown
 * or currently-unsupported ids are logged + skipped daemon-side; this
 * call still resolves successfully so listeners can fire on every event
 * without filtering.
 */
export async function sessionSwitchProvider(
  sessionId: SessionId,
  providerId: string,
): Promise<void> {
  await invoke('session_switch_provider', { sessionId, providerId });
}

/**
 * F-603: resume a paused session orchestrator. Idempotent — resuming a
 * session that is already running is a no-op and emits no event.
 */
export async function sessionResume(sessionId: SessionId): Promise<void> {
  await invoke('session_resume', { sessionId });
}

/**
 * F-604: interrupt the in-flight assistant turn and return the partial
 * text + capture anchors as a [`RefineHandoff`]. The webview drives the
 * refine composer from the returned value (or by handling
 * `Event::SessionInterrupted` on the stream — both shapes are equivalent).
 *
 * Calling this with no in-flight turn replies with an empty handoff
 * (`partial_text: ""`, both anchors empty); callers surface this as
 * "nothing to refine" rather than an error.
 */
export async function sessionInterruptAndRefine(
  sessionId: SessionId,
): Promise<RefineHandoff> {
  return invoke<RefineHandoff>('session_interrupt_and_refine', { sessionId });
}

/**
 * F-607: export the raw `events.jsonl` bytes for `sessionId`. The shell
 * accepts an empty `workspaceRoot` for session-window callers (server
 * resolves the cached workspace from `session_hello`); dashboard callers
 * pass the explicit workspace root they want to read.
 *
 * Returns the file bytes as a `Uint8Array` so the caller can hand them
 * directly to a `Blob` for download (or to `Tauri`'s save dialog if a
 * native picker becomes available later).
 */
export async function exportTranscript(
  sessionId: SessionId,
  workspaceRoot = '',
): Promise<Uint8Array> {
  const raw = await invoke<number[] | Uint8Array>('export_transcript', {
    sessionId,
    workspaceRoot,
  });
  return raw instanceof Uint8Array ? raw : new Uint8Array(raw);
}

/**
 * Switch the active variant for a branch group (F-145). `parentId` is the
 * root message id and `variantIndex` is the index into the group's
 * `variantIds` array.
 */
export async function selectBranch(
  sessionId: SessionId,
  parentId: string,
  variantIndex: number,
): Promise<void> {
  await invoke('select_branch', { sessionId, parentId, variantIndex });
}

/**
 * Delete a variant from a branch group (F-145). `parentId` is the root
 * message id and `variantIndex` is the index into the group's `variantIds`
 * array.
 */
export async function deleteBranch(
  sessionId: SessionId,
  parentId: string,
  variantIndex: number,
): Promise<void> {
  await invoke('delete_branch', { sessionId, parentId, variantIndex });
}

/**
 * F-598: trigger manual context compaction. The daemon emits
 * `Event::ContextCompacted` through the existing event stream when the
 * privileged summary call lands; the promise resolves once the IPC frame
 * is delivered (success of the underlying summary is observed via the
 * stream).
 */
export async function compactTranscript(sessionId: SessionId): Promise<void> {
  await invoke('compact_transcript', { sessionId });
}

/**
 * Re-run an assistant message with the chosen [`RerunVariant`] (F-143 /
 * F-144 / F-600). The Rust orchestrator dispatches:
 *
 * - `Replace` — truncate the transcript at `msgId` and regenerate in place.
 * - `Branch`  — keep the original; append a new variant under the same root.
 * - `Fresh`   — truncate to the originating user message and regenerate from
 *               there, producing a brand-new root.
 *
 * The shell binds this to `rerun_message`; backend dispatch error surfaces
 * as a rejected promise with a string reason.
 */
export async function rerunMessage(
  sessionId: SessionId,
  msgId: string,
  variant: RerunVariant,
): Promise<void> {
  await invoke('rerun_message', { sessionId, msgId, variant });
}

// ---------------------------------------------------------------------------
// F-151: persistent settings commands
// ---------------------------------------------------------------------------

/** Tier a `set_setting` write targets. */
export type SettingsLevel = 'user' | 'workspace';

/**
 * Load the merged user + workspace settings for the given workspace root.
 * The shell deep-merges at TOML-tree granularity — a workspace file that
 * declares only `[notifications]` does NOT overwrite the user's `[windows]`
 * preferences. Missing files on either tier fall through to defaults.
 */
export async function getSettings(workspaceRoot: string): Promise<AppSettings> {
  return invoke<AppSettings>('get_settings', { workspaceRoot });
}

/**
 * Persist a single setting at the requested tier. `key` is a dotted path
 * (e.g. `"notifications.bg_agents"`); `value` is the JSON-serializable scalar
 * (or table) to land at that location. The shell validates the value by
 * round-tripping the updated TOML tree through `AppSettings`, so bad types
 * are rejected before anything lands on disk.
 *
 * Sibling fields already present in the file survive — the backend applies
 * the update in-place on the raw TOML tree rather than serializing a full
 * struct, which is the guarantee that lets the merge semantic (workspace
 * overrides user on declared fields only) hold across repeated writes.
 */
export async function setSetting(
  key: string,
  value: unknown,
  level: SettingsLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('set_setting', { key, value, level, workspaceRoot });
}
